name: YUM Backend Rust Server

on:
  push:
    # branches: [ "main" ]
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: setup versioning
      id: vars
      run: |
        commit_short_hash="$(git rev-parse --short HEAD)"
        echo "commit_short_hash=$commit_short_hash" >> $GITHUB_OUTPUT
        echo "build_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

    - name: Build and push YUM Backend
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/web3nomad/yum-backend:latest
          ghcr.io/web3nomad/yum-backend:${{ steps.vars.outputs.commit_short_hash }}
          ghcr.io/web3nomad/yum-backend:${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64
